### PR TITLE
Configuration supported

### PR DESCRIPTION
**Pull request by fei0319**
Configuration is supported.

### CODE REVIEW

**Comment by Clouder0** [comment]
In my opinion, parsing args with [argparse](https://docs.python.org/3/library/argparse.html) may be a better approach.

**Comment by fei0319** [comment]
Seems a good idea.

**Comment by fei0319** [comment]
@Clouder0 The argparse is enabled.

**Review by Clouder0 — COMMENTED** [review]
Done.

**Comment by Clouder0** [comment]
Seems like I've just messed up the git history.  
A re-fork is needed probably.

**Comment by fei0319** [comment]
I don't understand what re-fork is actually. Can you instruct me about it?

**Comment by Clouder0** [comment]
> I don't understand what re-fork is actually. Can you instruct me about it?

Simply delete the forked repo and fork the origin repo again.

**Comment by fei0319** [comment]
Done.

**Pull request merged**
